#!/bin/bash

if [ $1 = "set" ]; then
    export http_proxy="http://bunburya:7istheBESTyeah@proxyA.tcd.ie:8080/"
    export https_proxy="http://bunburya:7istheBESTyeah@proxyA.tcd.ie:8080/"
    export ftp_proxy="http://bunburya:7istheBESTyeah@proxyA.tcd.ie:8080/"
    notify-send "Proxy set."
elif [ $1 = "unset" ]; then
    export http_proxy=""
    export https_proxy=""
    export ftp_proxy=""
    notify-send "Proxy unset."
fi
